// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klodelivkpiycxrbrzyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtsb2RlbGl2a3BpeWN4cmJyenlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODIyODAsImV4cCI6MjA2NDc1ODI4MH0.otVCIBxPhc_sdnmDlsZaVK2HLgiQ2vMnqRz_wI1fsrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);